id: P010386
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5519
  title: ལྷ་སའི་དམངས་ཁྲོད་ཀྱི་གླུ་གཞས།
  author: ''
  volumes:
    6173e7a66d234869ba826d06210803f4:
      image_group_id: I3CN5523
      title: ''
      volume_number: 1
      total_pages: 764
      base_file: v001.txt
    68ab7f90abb9458a84346e727e778d52:
      image_group_id: I3CN5524
      title: ''
      volume_number: 2
      total_pages: 800
      base_file: v002.txt
